// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "";

const char SSID[]               = "";    // Network SSID (name)
const char PASS[]               = "";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "";    // Secret device password

void onSpotifyNextChange();
void onSpotifyPlayPauseChange();
void onSpotifyPrevChange();
void onWakeOnLanChange();

CloudSwitch spotify_Next;
CloudSwitch spotifyPlayPause;
CloudSwitch spotify_Prev;
CloudSwitch wakeOnLan;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(spotify_Next, READWRITE, ON_CHANGE, onSpotifyNextChange);
  ArduinoCloud.addProperty(spotifyPlayPause, READWRITE, ON_CHANGE, onSpotifyPlayPauseChange);
  ArduinoCloud.addProperty(spotify_Prev, READWRITE, ON_CHANGE, onSpotifyPrevChange);
  ArduinoCloud.addProperty(wakeOnLan, READWRITE, ON_CHANGE, onWakeOnLanChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
